import { ConversionTool, ConversionCategory } from '@/types/converter';

export type { ConversionCategory };

export const conversionTools: ConversionTool[] = [
  // Documents
  {
    id: 'pdf-to-word',
    name: 'PDF to WORD',
    description: 'Convert PDF documents to editable Word format',
    fromFormat: 'pdf',
    toFormat: 'docx',
    category: 'documents',
    icon: 'file-pdf',
    iconColor: 'text-red-500',
    path: '/pdf-to-word',
    popular: true,
  },
  {
    id: 'word-to-pdf',
    name: 'WORD to PDF',
    description: 'Convert Word documents to PDF format',
    fromFormat: 'docx',
    toFormat: 'pdf',
    category: 'documents',
    icon: 'file-word',
    iconColor: 'text-blue-500',
    path: '/word-to-pdf',
    popular: true,
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to EXCEL',
    description: 'Convert PDF to Excel spreadsheet',
    fromFormat: 'pdf',
    toFormat: 'xlsx',
    category: 'documents',
    icon: 'file-excel',
    iconColor: 'text-green-500',
    path: '/pdf-to-excel',
  },
  {
    id: 'excel-to-pdf',
    name: 'EXCEL to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    fromFormat: 'xlsx',
    toFormat: 'pdf',
    category: 'documents',
    icon: 'file-excel',
    iconColor: 'text-green-500',
    path: '/excel-to-pdf',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PPT',
    description: 'Convert PDF to PowerPoint presentation',
    fromFormat: 'pdf',
    toFormat: 'pptx',
    category: 'documents',
    icon: 'file-powerpoint',
    iconColor: 'text-orange-500',
    path: '/pdf-to-ppt',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PPT to PDF',
    description: 'Convert PowerPoint to PDF format',
    fromFormat: 'pptx',
    toFormat: 'pdf',
    category: 'documents',
    icon: 'file-powerpoint',
    iconColor: 'text-orange-500',
    path: '/ppt-to-pdf',
  },
  {
    id: 'pdf-to-txt',
    name: 'PDF to TXT',
    description: 'Extract text from PDF documents',
    fromFormat: 'pdf',
    toFormat: 'txt',
    category: 'documents',
    icon: 'file-alt',
    iconColor: 'text-gray-500',
    path: '/pdf-to-txt',
  },
  {
    id: 'excel-to-csv',
    name: 'EXCEL to CSV',
    description: 'Convert Excel files to CSV format',
    fromFormat: 'xlsx',
    toFormat: 'csv',
    category: 'documents',
    icon: 'file-csv',
    iconColor: 'text-green-600',
    path: '/excel-to-csv',
  },

  // Images
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    description: 'Convert JPEG images to PNG format',
    fromFormat: 'jpg',
    toFormat: 'png',
    category: 'images',
    icon: 'image',
    iconColor: 'text-blue-500',
    path: '/jpg-to-png',
    popular: true,
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    description: 'Convert PNG images to JPEG format',
    fromFormat: 'png',
    toFormat: 'jpg',
    category: 'images',
    icon: 'image',
    iconColor: 'text-purple-500',
    path: '/png-to-jpg',
    popular: true,
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WEBP',
    description: 'Convert JPEG to modern WebP format',
    fromFormat: 'jpg',
    toFormat: 'webp',
    category: 'images',
    icon: 'image',
    iconColor: 'text-green-500',
    path: '/jpg-to-webp',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    description: 'Convert PNG images to PDF documents',
    fromFormat: 'png',
    toFormat: 'pdf',
    category: 'images',
    icon: 'file-pdf',
    iconColor: 'text-red-500',
    path: '/png-to-pdf',
  },
  {
    id: 'svg-to-png',
    name: 'SVG to PNG',
    description: 'Convert vector SVG to raster PNG',
    fromFormat: 'svg',
    toFormat: 'png',
    category: 'images',
    icon: 'vector-square',
    iconColor: 'text-orange-500',
    path: '/svg-to-png',
  },
  {
    id: 'heic-to-jpg',
    name: 'HEIC to JPG',
    description: 'Convert iPhone HEIC photos to JPEG',
    fromFormat: 'heic',
    toFormat: 'jpg',
    category: 'images',
    icon: 'smartphone',
    iconColor: 'text-gray-500',
    path: '/heic-to-jpg',
  },
  {
    id: 'gif-to-mp4',
    name: 'GIF to MP4',
    description: 'Convert animated GIF to MP4 video',
    fromFormat: 'gif',
    toFormat: 'mp4',
    category: 'images',
    icon: 'film',
    iconColor: 'text-pink-500',
    path: '/gif-to-mp4',
  },
  {
    id: 'image-compressor',
    name: 'Compress Image',
    description: 'Reduce image file size',
    fromFormat: 'any',
    toFormat: 'compressed',
    category: 'images',
    icon: 'compress',
    iconColor: 'text-indigo-500',
    path: '/image-compressor',
  },

  // Audio
  {
    id: 'mp3-to-wav',
    name: 'MP3 to WAV',
    description: 'Convert MP3 audio to WAV format',
    fromFormat: 'mp3',
    toFormat: 'wav',
    category: 'audio',
    icon: 'volume-2',
    iconColor: 'text-blue-500',
    path: '/mp3-to-wav',
    popular: true,
  },
  {
    id: 'wav-to-mp3',
    name: 'WAV to MP3',
    description: 'Convert WAV audio to MP3 format',
    fromFormat: 'wav',
    toFormat: 'mp3',
    category: 'audio',
    icon: 'music',
    iconColor: 'text-purple-500',
    path: '/wav-to-mp3',
  },
  {
    id: 'flac-to-mp3',
    name: 'FLAC to MP3',
    description: 'Convert FLAC audio to MP3 format',
    fromFormat: 'flac',
    toFormat: 'mp3',
    category: 'audio',
    icon: 'headphones',
    iconColor: 'text-green-500',
    path: '/flac-to-mp3',
  },
  {
    id: 'm4a-to-mp3',
    name: 'M4A to MP3',
    description: 'Convert M4A audio to MP3 format',
    fromFormat: 'm4a',
    toFormat: 'mp3',
    category: 'audio',
    icon: 'music',
    iconColor: 'text-orange-500',
    path: '/m4a-to-mp3',
  },
  {
    id: 'ogg-to-mp3',
    name: 'OGG to MP3',
    description: 'Convert OGG audio to MP3 format',
    fromFormat: 'ogg',
    toFormat: 'mp3',
    category: 'audio',
    icon: 'volume-2',
    iconColor: 'text-red-500',
    path: '/ogg-to-mp3',
  },
  {
    id: 'mp3-to-aac',
    name: 'MP3 to AAC',
    description: 'Convert MP3 to AAC audio format',
    fromFormat: 'mp3',
    toFormat: 'aac',
    category: 'audio',
    icon: 'radio',
    iconColor: 'text-indigo-500',
    path: '/mp3-to-aac',
  },
  {
    id: 'audio-to-text',
    name: 'Audio to Text',
    description: 'Transcribe audio to text using speech recognition',
    fromFormat: 'audio',
    toFormat: 'text',
    category: 'other',
    icon: 'mic',
    iconColor: 'text-teal-500',
    path: '/audio-to-text',
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to audio speech',
    fromFormat: 'text',
    toFormat: 'audio',
    category: 'other',
    icon: 'message-circle',
    iconColor: 'text-pink-500',
    path: '/text-to-speech',
  },

  // Video
  {
    id: 'mp4-to-avi',
    name: 'MP4 to AVI',
    description: 'Convert MP4 videos to AVI format',
    fromFormat: 'mp4',
    toFormat: 'avi',
    category: 'video',
    icon: 'video',
    iconColor: 'text-blue-500',
    path: '/mp4-to-avi',
    popular: true,
  },
  {
    id: 'avi-to-mp4',
    name: 'AVI to MP4',
    description: 'Convert AVI videos to MP4 format',
    fromFormat: 'avi',
    toFormat: 'mp4',
    category: 'video',
    icon: 'film',
    iconColor: 'text-purple-500',
    path: '/avi-to-mp4',
  },
  {
    id: 'mp4-to-mov',
    name: 'MP4 to MOV',
    description: 'Convert MP4 to QuickTime MOV format',
    fromFormat: 'mp4',
    toFormat: 'mov',
    category: 'video',
    icon: 'video',
    iconColor: 'text-green-500',
    path: '/mp4-to-mov',
  },
  {
    id: 'mp4-to-mkv',
    name: 'MP4 to MKV',
    description: 'Convert MP4 to Matroska MKV format',
    fromFormat: 'mp4',
    toFormat: 'mkv',
    category: 'video',
    icon: 'play',
    iconColor: 'text-orange-500',
    path: '/mp4-to-mkv',
  },
  {
    id: 'mp4-to-webm',
    name: 'MP4 to WEBM',
    description: 'Convert MP4 to web-optimized WEBM',
    fromFormat: 'mp4',
    toFormat: 'webm',
    category: 'video',
    icon: 'globe',
    iconColor: 'text-red-500',
    path: '/mp4-to-webm',
  },
  {
    id: 'extract-mp3-from-mp4',
    name: 'Extract Audio',
    description: 'Extract MP3 audio from MP4 video',
    fromFormat: 'mp4',
    toFormat: 'mp3',
    category: 'video',
    icon: 'music',
    iconColor: 'text-indigo-500',
    path: '/extract-mp3-from-mp4',
  },
  {
    id: 'compress-mp4',
    name: 'Compress Video',
    description: 'Reduce MP4 video file size',
    fromFormat: 'mp4',
    toFormat: 'compressed',
    category: 'video',
    icon: 'minimize-2',
    iconColor: 'text-teal-500',
    path: '/compress-mp4',
  },

  // Archives
  {
    id: 'zip-to-rar',
    name: 'ZIP to RAR',
    description: 'Convert ZIP archives to RAR format',
    fromFormat: 'zip',
    toFormat: 'rar',
    category: 'archives',
    icon: 'archive',
    iconColor: 'text-blue-500',
    path: '/zip-to-rar',
  },
  {
    id: 'rar-to-zip',
    name: 'RAR to ZIP',
    description: 'Convert RAR archives to ZIP format',
    fromFormat: 'rar',
    toFormat: 'zip',
    category: 'archives',
    icon: 'archive',
    iconColor: 'text-purple-500',
    path: '/rar-to-zip',
  },
  {
    id: 'zip-to-7z',
    name: 'ZIP to 7Z',
    description: 'Convert ZIP to 7-Zip format',
    fromFormat: 'zip',
    toFormat: '7z',
    category: 'archives',
    icon: 'archive',
    iconColor: 'text-green-500',
    path: '/zip-to-7z',
  },
  {
    id: 'tar-to-zip',
    name: 'TAR to ZIP',
    description: 'Convert TAR archives to ZIP format',
    fromFormat: 'tar',
    toFormat: 'zip',
    category: 'archives',
    icon: 'folder',
    iconColor: 'text-orange-500',
    path: '/tar-to-zip',
  },
  {
    id: 'iso-to-zip',
    name: 'ISO to ZIP',
    description: 'Extract ISO disk images to ZIP',
    fromFormat: 'iso',
    toFormat: 'zip',
    category: 'archives',
    icon: 'disc',
    iconColor: 'text-red-500',
    path: '/iso-to-zip',
  },
  {
    id: 'file-compressor',
    name: 'Compress Files',
    description: 'Create compressed archive from files',
    fromFormat: 'files',
    toFormat: 'zip',
    category: 'archives',
    icon: 'minimize',
    iconColor: 'text-indigo-500',
    path: '/file-compressor',
  },

  // Other Tools
  {
    id: 'image-to-text',
    name: 'Image to Text (OCR)',
    description: 'Extract text from images using OCR',
    fromFormat: 'image',
    toFormat: 'text',
    category: 'other',
    icon: 'eye',
    iconColor: 'text-blue-500',
    path: '/image-to-text',
  },
  {
    id: 'speech-to-text',
    name: 'Speech to Text',
    description: 'Transcribe speech audio to text',
    fromFormat: 'audio',
    toFormat: 'text',
    category: 'other',
    icon: 'mic',
    iconColor: 'text-purple-500',
    path: '/speech-to-text',
  },
  {
    id: 'epub-to-pdf',
    name: 'EPUB to PDF',
    description: 'Convert EPUB ebooks to PDF format',
    fromFormat: 'epub',
    toFormat: 'pdf',
    category: 'other',
    icon: 'book',
    iconColor: 'text-green-500',
    path: '/epub-to-pdf',
  },
  {
    id: 'mobi-to-pdf',
    name: 'MOBI to PDF',
    description: 'Convert MOBI ebooks to PDF format',
    fromFormat: 'mobi',
    toFormat: 'pdf',
    category: 'other',
    icon: 'book-open',
    iconColor: 'text-orange-500',
    path: '/mobi-to-pdf',
  },
];

export const getToolsByCategory = (category: ConversionCategory): ConversionTool[] => {
  return conversionTools.filter(tool => tool.category === category);
};

export const getPopularTools = (): ConversionTool[] => {
  return conversionTools.filter(tool => tool.popular);
};

export const getToolById = (id: string): ConversionTool | undefined => {
  return conversionTools.find(tool => tool.id === id);
};

export const getToolByPath = (path: string): ConversionTool | undefined => {
  return conversionTools.find(tool => tool.path === path);
};

export const categories: { id: ConversionCategory; name: string; icon: string }[] = [
  { id: 'documents', name: 'Documents', icon: 'file-text' },
  { id: 'images', name: 'Images', icon: 'image' },
  { id: 'audio', name: 'Audio', icon: 'volume-2' },
  { id: 'video', name: 'Video', icon: 'video' },
  { id: 'archives', name: 'Archives', icon: 'archive' },
  { id: 'other', name: 'Other Tools', icon: 'settings' },
];
